"""Add foreign keys

Revision ID: aa1284ca1d9c
Revises: be8fc03d1d43
Create Date: 2023-01-29 03:59:00.926156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa1284ca1d9c'
down_revision = 'be8fc03d1d43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chats', 'users', ['creator_id'], ['id'])
    op.add_column('messages', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('destination_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'users', ['destination_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['creator_id'], ['id'])
    op.add_column('users', sa.Column('active_chat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'chats', ['active_chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'active_chat_id')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'destination_id')
    op.drop_column('messages', 'creator_id')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'creator_id')
    # ### end Alembic commands ###
