"""Add avatar thumbnails

Revision ID: d76a8767fb18
Revises: 1b5e2ee66f4b
Create Date: 2023-01-30 13:59:21.679815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd76a8767fb18'
down_revision = '1b5e2ee66f4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ava050', sa.String(), nullable=True))
    op.add_column('users', sa.Column('ava100', sa.String(), nullable=True))
    op.add_column('users', sa.Column('ava400', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ava400')
    op.drop_column('users', 'ava100')
    op.drop_column('users', 'ava050')
    # ### end Alembic commands ###
